In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("housing.csv")

In [4]:
df.shape

(20640, 10)

In [5]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [8]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [9]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [10]:
df['total_bedrooms'].fillna(df['total_bedrooms'].median(), inplace=True)

C:\Users\muabd\AppData\Local\Temp\ipykernel_17100\1590527289.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['total_bedrooms'].fillna(df['total_bedrooms'].median(), inplace=True)

In [11]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [12]:
df = pd.get_dummies(df, columns=['ocean_proximity'], drop_first=True)

In [13]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,True,False

In [14]:
X = df['median_income'].values
y = df['median_house_value'].values

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
print(X_train.shape)
print(X_test.shape)

(16512,)
(4128,)

# Manual Processing using NumPy

In [18]:
x_mean = np.mean(X_train)
y_mean = np.mean(y_train)

In [19]:
num = np.sum((X_train - x_mean) * (y_train - y_mean))
denom = np.sum((X_train - x_mean) ** 2)

In [20]:
m = num / denom
b = y_mean - m * x_mean

In [21]:
print(f"Slope     (m): {m:.2f}")
print(f"Intercept (b): {b:.2f}")
print(f"House Value = {m:.2f} x median_income + {b:.2f}")

Slope     (m): 41933.85
Intercept (b): 44459.73
House Value = 41933.85 x median_income + 44459.73

In [22]:
y_pred = m * X_test + b

In [23]:
mae = np.mean(np.abs(y_test - y_pred))
mse = np.mean((y_test - y_pred) ** 2)
rmse = np.sqrt(mse)

In [30]:
ss_res = np.sum((y_test - y_pred) ** 2)
ss_tot = np.sum((y_test - y_mean) ** 2)

r2 = 1 - (ss_res / ss_tot)

In [32]:
n = len(y)
k = 1

adj_r2 = 1 - (1 - r2) * (n - 1) / (n - k - 1)

In [33]:
print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R Sqr: {r2}")
print(f"Adj R Sqr: {adj_r2}")

MAE: 62990.86530093761
MSE: 7091157771.76555
RMSE: 84209.01241414454
R Sqr: 0.45897772006565896
Adj R Sqr: 0.45895150520569505

# Verfication using Scikit-Learn

In [43]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [40]:
model = LinearRegression()
model.fit(X_train.reshape(-1,1), y_train)

LinearRegression()

In [42]:
y_pred = model.predict(X_test.reshape(-1,1))

In [45]:
mae_sklearn = mean_absolute_error(y_test, y_pred)
mse_sklearn = mean_squared_error(y_test, y_pred)
rmse_sklearn = np.sqrt(mse_sklearn)
r2_sklearn = r2_score(y_test, y_pred)

In [46]:
print(f"MAE: {mae_sklearn}")
print(f"MSE: {mse_sklearn}")
print(f"RMSE: {rmse_sklearn}")
print(f"R Sqr: {r2_sklearn}")

MAE: 62990.86530093761
MSE: 7091157771.76555
RMSE: 84209.01241414454
R Sqr: 0.45885918903846656

# Comparison

In [48]:
print("Manual MAE:", mae)
print("Sklearn MAE:", mae_sklearn)

print("\nManual MSE:", mse)
print("Sklearn MSE:", mse_sklearn)

print("\nManual RMSE:", rmse)
print("Sklearn RMSE:", rmse_sklearn)

print("\nManual R2:", r2)
print("Sklearn R2:", r2_sklearn)

print("\nManual Adjusted R2:", adj_r2)

Manual MAE: 62990.86530093761
Sklearn MAE: 62990.86530093761

Manual MSE: 7091157771.76555
Sklearn MSE: 7091157771.76555

Manual RMSE: 84209.01241414454
Sklearn RMSE: 84209.01241414454

Manual R2: 0.45897772006565896
Sklearn R2: 0.45885918903846656

Manual Adjusted R2: 0.45895150520569505